# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98d14b716a374723ad57fea844cdd4a72eef513fcf4ddb52a36c6cc8613e12cf20b0cb4a6e687153c62e6071ebe8385dd74276733a8537d349b8611a8aa0027d

test:
  secret_key_base: e703432b80e7e3f22391d47cb1fdc2314595d2475546b43dbf4fff2f4ff384087554cdaba8befc4d542d2597d27aa2495c6122d07d641abd73679996f078cdac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
